version: "3.8"
services:
  db:
    image: mysql-for-node
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: node_express
    ports:
      - "3307:3306"
    restart: always
  web:
    image: node-express-crud
    build: ./
    environment:
      MYSQL_DATABASE: node_express
      MYSQL_USER: root
      MYSQL_PASSWORD: 123123
      MYSQL_HOST: db
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure
